/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.asta.isoObject;

public class AccelerationType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AccelerationType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AccelerationType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObject_wrapJNI.delete_AccelerationType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLongitudinal_m_s2(double value) {
    isoObject_wrapJNI.AccelerationType_longitudinal_m_s2_set(swigCPtr, this, value);
  }

  public double getLongitudinal_m_s2() {
    return isoObject_wrapJNI.AccelerationType_longitudinal_m_s2_get(swigCPtr, this);
  }

  public void setLateral_m_s2(double value) {
    isoObject_wrapJNI.AccelerationType_lateral_m_s2_set(swigCPtr, this, value);
  }

  public double getLateral_m_s2() {
    return isoObject_wrapJNI.AccelerationType_lateral_m_s2_get(swigCPtr, this);
  }

  public void setIsLongitudinalValid(boolean value) {
    isoObject_wrapJNI.AccelerationType_isLongitudinalValid_set(swigCPtr, this, value);
  }

  public boolean getIsLongitudinalValid() {
    return isoObject_wrapJNI.AccelerationType_isLongitudinalValid_get(swigCPtr, this);
  }

  public void setIsLateralValid(boolean value) {
    isoObject_wrapJNI.AccelerationType_isLateralValid_set(swigCPtr, this, value);
  }

  public boolean getIsLateralValid() {
    return isoObject_wrapJNI.AccelerationType_isLateralValid_get(swigCPtr, this);
  }

  public AccelerationType() {
    this(isoObject_wrapJNI.new_AccelerationType(), true);
  }

}
