/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.asta.isoObject;

public class CartesianPosition {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CartesianPosition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CartesianPosition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObject_wrapJNI.delete_CartesianPosition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXCoord_m(double value) {
    isoObject_wrapJNI.CartesianPosition_xCoord_m_set(swigCPtr, this, value);
  }

  public double getXCoord_m() {
    return isoObject_wrapJNI.CartesianPosition_xCoord_m_get(swigCPtr, this);
  }

  public void setYCoord_m(double value) {
    isoObject_wrapJNI.CartesianPosition_yCoord_m_set(swigCPtr, this, value);
  }

  public double getYCoord_m() {
    return isoObject_wrapJNI.CartesianPosition_yCoord_m_get(swigCPtr, this);
  }

  public void setZCoord_m(double value) {
    isoObject_wrapJNI.CartesianPosition_zCoord_m_set(swigCPtr, this, value);
  }

  public double getZCoord_m() {
    return isoObject_wrapJNI.CartesianPosition_zCoord_m_get(swigCPtr, this);
  }

  public void setHeading_rad(double value) {
    isoObject_wrapJNI.CartesianPosition_heading_rad_set(swigCPtr, this, value);
  }

  public double getHeading_rad() {
    return isoObject_wrapJNI.CartesianPosition_heading_rad_get(swigCPtr, this);
  }

  public void setIsPositionValid(boolean value) {
    isoObject_wrapJNI.CartesianPosition_isPositionValid_set(swigCPtr, this, value);
  }

  public boolean getIsPositionValid() {
    return isoObject_wrapJNI.CartesianPosition_isPositionValid_get(swigCPtr, this);
  }

  public void setIsHeadingValid(boolean value) {
    isoObject_wrapJNI.CartesianPosition_isHeadingValid_set(swigCPtr, this, value);
  }

  public boolean getIsHeadingValid() {
    return isoObject_wrapJNI.CartesianPosition_isHeadingValid_get(swigCPtr, this);
  }

  public void setIsXcoordValid(boolean value) {
    isoObject_wrapJNI.CartesianPosition_isXcoordValid_set(swigCPtr, this, value);
  }

  public boolean getIsXcoordValid() {
    return isoObject_wrapJNI.CartesianPosition_isXcoordValid_get(swigCPtr, this);
  }

  public void setIsYcoordValid(boolean value) {
    isoObject_wrapJNI.CartesianPosition_isYcoordValid_set(swigCPtr, this, value);
  }

  public boolean getIsYcoordValid() {
    return isoObject_wrapJNI.CartesianPosition_isYcoordValid_get(swigCPtr, this);
  }

  public void setIsZcoordValid(boolean value) {
    isoObject_wrapJNI.CartesianPosition_isZcoordValid_set(swigCPtr, this, value);
  }

  public boolean getIsZcoordValid() {
    return isoObject_wrapJNI.CartesianPosition_isZcoordValid_get(swigCPtr, this);
  }

  public CartesianPosition() {
    this(isoObject_wrapJNI.new_CartesianPosition(), true);
  }

}
