/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asta.isoObject;

public class Server extends BasicSocket {
  private transient long swigCPtr;

  protected Server(long cPtr, boolean cMemoryOwn) {
    super(isoObject_wrapJNI.Server_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Server obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObject_wrapJNI.delete_Server(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Server(BasicSocket.SocketType type, boolean debug) {
    this(isoObject_wrapJNI.new_Server__SWIG_0(type.swigValue(), debug), true);
  }

  public Server(BasicSocket.SocketType type) {
    this(isoObject_wrapJNI.new_Server__SWIG_1(type.swigValue()), true);
  }

  public Server(BasicSocket.SocketType type, String localAddr, int port, boolean debug) {
    this(isoObject_wrapJNI.new_Server__SWIG_2(type.swigValue(), localAddr, port, debug), true);
  }

  public Server(BasicSocket.SocketType type, String localAddr, int port) {
    this(isoObject_wrapJNI.new_Server__SWIG_3(type.swigValue(), localAddr, port), true);
  }

}
