/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
package com.asta.isoObject;


public class Socket extends BasicSocket {
  private transient long swigCPtr;

  protected Socket(long cPtr, boolean cMemoryOwn) {
    super(isoObject_wrapJNI.Socket_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Socket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObject_wrapJNI.delete_Socket(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Socket(Socket other) {
    this(isoObject_wrapJNI.new_Socket__SWIG_0(Socket.getCPtr(other), other), true);
  }

  public SWIGTYPE_p_std__vectorT_char_t recv() {
    return new SWIGTYPE_p_std__vectorT_char_t(isoObject_wrapJNI.Socket_recv(swigCPtr, this), true);
  }

  public void send(SWIGTYPE_p_std__vectorT_char_t data) {
    isoObject_wrapJNI.Socket_send__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(data));
  }

  public void send(SWIGTYPE_p_std__vectorT_char_t data, long nBytes) {
    isoObject_wrapJNI.Socket_send__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(data), nBytes);
  }

}
