/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asta.isoObject;

public class TCPServer extends Server {
  private transient long swigCPtr;

  protected TCPServer(long cPtr, boolean cMemoryOwn) {
    super(isoObject_wrapJNI.TCPServer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TCPServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObject_wrapJNI.delete_TCPServer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TCPServer(boolean debug) {
    this(isoObject_wrapJNI.new_TCPServer__SWIG_0(debug), true);
  }

  public TCPServer() {
    this(isoObject_wrapJNI.new_TCPServer__SWIG_1(), true);
  }

  public TCPServer(String localAddr, int port, boolean debug) {
    this(isoObject_wrapJNI.new_TCPServer__SWIG_2(localAddr, port, debug), true);
  }

  public TCPServer(String localAddr, int port) {
    this(isoObject_wrapJNI.new_TCPServer__SWIG_3(localAddr, port), true);
  }

  public Socket await() {
    return new Socket(isoObject_wrapJNI.TCPServer_await__SWIG_0(swigCPtr, this), true);
  }

  public Socket await(String localAddr, int port) {
    return new Socket(isoObject_wrapJNI.TCPServer_await__SWIG_1(swigCPtr, this, localAddr, port), true);
  }

}
