/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.asta.isoObject;

public class UDPServer extends Server {
  private transient long swigCPtr;

  protected UDPServer(long cPtr, boolean cMemoryOwn) {
    super(isoObject_wrapJNI.UDPServer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UDPServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObject_wrapJNI.delete_UDPServer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public UDPServer(boolean debug) {
    this(isoObject_wrapJNI.new_UDPServer__SWIG_0(debug), true);
  }

  public UDPServer() {
    this(isoObject_wrapJNI.new_UDPServer__SWIG_1(), true);
  }

  public UDPServer(String localAddr, int port, boolean debug) {
    this(isoObject_wrapJNI.new_UDPServer__SWIG_2(localAddr, port, debug), true);
  }

  public UDPServer(String localAddr, int port) {
    this(isoObject_wrapJNI.new_UDPServer__SWIG_3(localAddr, port), true);
  }

  public void bind(BasicSocket.HostInfo localEndpoint) {
    isoObject_wrapJNI.UDPServer_bind(swigCPtr, this, BasicSocket.HostInfo.getCPtr(localEndpoint), localEndpoint);
  }

  public SWIGTYPE_p_std__pairT_std__vectorT_char_t_BasicSocket__HostInfo_t recvfrom() {
    return new SWIGTYPE_p_std__pairT_std__vectorT_char_t_BasicSocket__HostInfo_t(isoObject_wrapJNI.UDPServer_recvfrom(swigCPtr, this), true);
  }

  public void sendto(SWIGTYPE_p_std__pairT_std__vectorT_char_t_const_BasicSocket__HostInfo_const_t data) {
    isoObject_wrapJNI.UDPServer_sendto__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__pairT_std__vectorT_char_t_const_BasicSocket__HostInfo_const_t.getCPtr(data));
  }

  public void sendto(SWIGTYPE_p_std__pairT_std__vectorT_char_t_const_BasicSocket__HostInfo_const_t data, long nBytes) {
    isoObject_wrapJNI.UDPServer_sendto__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__pairT_std__vectorT_char_t_const_BasicSocket__HostInfo_const_t.getCPtr(data), nBytes);
  }

}
