/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public final class ActionType_t {
  public final static ActionType_t ACTION_NONE = new ActionType_t("ACTION_NONE", isoObjectJNI.ACTION_NONE_get());
  public final static ActionType_t ACTION_TYPE_1 = new ActionType_t("ACTION_TYPE_1", isoObjectJNI.ACTION_TYPE_1_get());
  public final static ActionType_t ACTION_TYPE_2 = new ActionType_t("ACTION_TYPE_2", isoObjectJNI.ACTION_TYPE_2_get());
  public final static ActionType_t ACTION_SET_SPEED = new ActionType_t("ACTION_SET_SPEED", isoObjectJNI.ACTION_SET_SPEED_get());
  public final static ActionType_t ACTION_SET_DISTANCE = new ActionType_t("ACTION_SET_DISTANCE", isoObjectJNI.ACTION_SET_DISTANCE_get());
  public final static ActionType_t ACTION_SET_ACCELERATION = new ActionType_t("ACTION_SET_ACCELERATION", isoObjectJNI.ACTION_SET_ACCELERATION_get());
  public final static ActionType_t ACTION_LANE_CHANGE = new ActionType_t("ACTION_LANE_CHANGE", isoObjectJNI.ACTION_LANE_CHANGE_get());
  public final static ActionType_t ACTION_LANE_OFFSET = new ActionType_t("ACTION_LANE_OFFSET", isoObjectJNI.ACTION_LANE_OFFSET_get());
  public final static ActionType_t ACTION_SET_POSITION = new ActionType_t("ACTION_SET_POSITION", isoObjectJNI.ACTION_SET_POSITION_get());
  public final static ActionType_t ACTION_SET_STEERING_ANGLE = new ActionType_t("ACTION_SET_STEERING_ANGLE", isoObjectJNI.ACTION_SET_STEERING_ANGLE_get());
  public final static ActionType_t ACTION_SET_TRHOTTLE_VALUE = new ActionType_t("ACTION_SET_TRHOTTLE_VALUE", isoObjectJNI.ACTION_SET_TRHOTTLE_VALUE_get());
  public final static ActionType_t ACTION_BRAKE = new ActionType_t("ACTION_BRAKE", isoObjectJNI.ACTION_BRAKE_get());
  public final static ActionType_t ACTION_FOLLOW_TRAJECTORY = new ActionType_t("ACTION_FOLLOW_TRAJECTORY", isoObjectJNI.ACTION_FOLLOW_TRAJECTORY_get());
  public final static ActionType_t ACTION_OTHER_OBJECT_FEATURE = new ActionType_t("ACTION_OTHER_OBJECT_FEATURE", isoObjectJNI.ACTION_OTHER_OBJECT_FEATURE_get());
  public final static ActionType_t ACTION_INFRASTRUCTURE = new ActionType_t("ACTION_INFRASTRUCTURE", isoObjectJNI.ACTION_INFRASTRUCTURE_get());
  public final static ActionType_t ACTION_TEST_SCENARIO_COMMAND = new ActionType_t("ACTION_TEST_SCENARIO_COMMAND", isoObjectJNI.ACTION_TEST_SCENARIO_COMMAND_get());
  public final static ActionType_t ACTION_MISC_DIGITAL_OUTPUT = new ActionType_t("ACTION_MISC_DIGITAL_OUTPUT", isoObjectJNI.ACTION_MISC_DIGITAL_OUTPUT_get());
  public final static ActionType_t ACTION_MISC_ANALOG_OUTPUT = new ActionType_t("ACTION_MISC_ANALOG_OUTPUT", isoObjectJNI.ACTION_MISC_ANALOG_OUTPUT_get());
  public final static ActionType_t ACTION_START_TIMER = new ActionType_t("ACTION_START_TIMER", isoObjectJNI.ACTION_START_TIMER_get());
  public final static ActionType_t ACTION_MODE_CHANGE = new ActionType_t("ACTION_MODE_CHANGE", isoObjectJNI.ACTION_MODE_CHANGE_get());
  public final static ActionType_t ACTION_UNAVAILABLE = new ActionType_t("ACTION_UNAVAILABLE", isoObjectJNI.ACTION_UNAVAILABLE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ActionType_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ActionType_t.class + " with value " + swigValue);
  }

  private ActionType_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ActionType_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ActionType_t(String swigName, ActionType_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ActionType_t[] swigValues = { ACTION_NONE, ACTION_TYPE_1, ACTION_TYPE_2, ACTION_SET_SPEED, ACTION_SET_DISTANCE, ACTION_SET_ACCELERATION, ACTION_LANE_CHANGE, ACTION_LANE_OFFSET, ACTION_SET_POSITION, ACTION_SET_STEERING_ANGLE, ACTION_SET_TRHOTTLE_VALUE, ACTION_BRAKE, ACTION_FOLLOW_TRAJECTORY, ACTION_OTHER_OBJECT_FEATURE, ACTION_INFRASTRUCTURE, ACTION_TEST_SCENARIO_COMMAND, ACTION_MISC_DIGITAL_OUTPUT, ACTION_MISC_ANALOG_OUTPUT, ACTION_START_TIMER, ACTION_MODE_CHANGE, ACTION_UNAVAILABLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

