/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public final class ActionTypeParameter_t {
  public final static ActionTypeParameter_t ACTION_PARAMETER_SET_FALSE = new ActionTypeParameter_t("ACTION_PARAMETER_SET_FALSE", isoObjectJNI.ACTION_PARAMETER_SET_FALSE_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_SET_TRUE = new ActionTypeParameter_t("ACTION_PARAMETER_SET_TRUE", isoObjectJNI.ACTION_PARAMETER_SET_TRUE_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_RELEASE = new ActionTypeParameter_t("ACTION_PARAMETER_RELEASE", isoObjectJNI.ACTION_PARAMETER_RELEASE_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_PRESS = new ActionTypeParameter_t("ACTION_PARAMETER_PRESS", isoObjectJNI.ACTION_PARAMETER_PRESS_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_SET_VALUE = new ActionTypeParameter_t("ACTION_PARAMETER_SET_VALUE", isoObjectJNI.ACTION_PARAMETER_SET_VALUE_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_MIN = new ActionTypeParameter_t("ACTION_PARAMETER_MIN", isoObjectJNI.ACTION_PARAMETER_MIN_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_MAX = new ActionTypeParameter_t("ACTION_PARAMETER_MAX", isoObjectJNI.ACTION_PARAMETER_MAX_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_X = new ActionTypeParameter_t("ACTION_PARAMETER_X", isoObjectJNI.ACTION_PARAMETER_X_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_Y = new ActionTypeParameter_t("ACTION_PARAMETER_Y", isoObjectJNI.ACTION_PARAMETER_Y_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_Z = new ActionTypeParameter_t("ACTION_PARAMETER_Z", isoObjectJNI.ACTION_PARAMETER_Z_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_VS_BRAKE_WARNING = new ActionTypeParameter_t("ACTION_PARAMETER_VS_BRAKE_WARNING", isoObjectJNI.ACTION_PARAMETER_VS_BRAKE_WARNING_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_VS_SEND_START = new ActionTypeParameter_t("ACTION_PARAMETER_VS_SEND_START", isoObjectJNI.ACTION_PARAMETER_VS_SEND_START_get());
  public final static ActionTypeParameter_t ACTION_PARAMETER_UNAVAILABLE = new ActionTypeParameter_t("ACTION_PARAMETER_UNAVAILABLE", isoObjectJNI.ACTION_PARAMETER_UNAVAILABLE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ActionTypeParameter_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ActionTypeParameter_t.class + " with value " + swigValue);
  }

  private ActionTypeParameter_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ActionTypeParameter_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ActionTypeParameter_t(String swigName, ActionTypeParameter_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ActionTypeParameter_t[] swigValues = { ACTION_PARAMETER_SET_FALSE, ACTION_PARAMETER_SET_TRUE, ACTION_PARAMETER_RELEASE, ACTION_PARAMETER_PRESS, ACTION_PARAMETER_SET_VALUE, ACTION_PARAMETER_MIN, ACTION_PARAMETER_MAX, ACTION_PARAMETER_X, ACTION_PARAMETER_Y, ACTION_PARAMETER_Z, ACTION_PARAMETER_VS_BRAKE_WARNING, ACTION_PARAMETER_VS_SEND_START, ACTION_PARAMETER_UNAVAILABLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

