/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class DctiMessageDataType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DctiMessageDataType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DctiMessageDataType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_DctiMessageDataType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTotalCount(int value) {
    isoObjectJNI.DctiMessageDataType_totalCount_set(swigCPtr, this, value);
  }

  public int getTotalCount() {
    return isoObjectJNI.DctiMessageDataType_totalCount_get(swigCPtr, this);
  }

  public void setCounter(int value) {
    isoObjectJNI.DctiMessageDataType_counter_set(swigCPtr, this, value);
  }

  public int getCounter() {
    return isoObjectJNI.DctiMessageDataType_counter_get(swigCPtr, this);
  }

  public void setTransmitterID(long value) {
    isoObjectJNI.DctiMessageDataType_transmitterID_set(swigCPtr, this, value);
  }

  public long getTransmitterID() {
    return isoObjectJNI.DctiMessageDataType_transmitterID_get(swigCPtr, this);
  }

  public DctiMessageDataType() {
    this(isoObjectJNI.new_DctiMessageDataType(), true);
  }

}
