/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public final class GeneralResponseStatus {
  public final static GeneralResponseStatus GREM_STATUS_OK = new GeneralResponseStatus("GREM_STATUS_OK", isoObjectJNI.GREM_STATUS_OK_get());
  public final static GeneralResponseStatus GREM_DATA_MISSING = new GeneralResponseStatus("GREM_DATA_MISSING", isoObjectJNI.GREM_DATA_MISSING_get());
  public final static GeneralResponseStatus GREM_STATE_ERROR = new GeneralResponseStatus("GREM_STATE_ERROR", isoObjectJNI.GREM_STATE_ERROR_get());
  public final static GeneralResponseStatus GREM_TIME_SLIPPAGE = new GeneralResponseStatus("GREM_TIME_SLIPPAGE", isoObjectJNI.GREM_TIME_SLIPPAGE_get());
  public final static GeneralResponseStatus GREM_WRONG_ID = new GeneralResponseStatus("GREM_WRONG_ID", isoObjectJNI.GREM_WRONG_ID_get());
  public final static GeneralResponseStatus GREM_OUT_OF_RANGE = new GeneralResponseStatus("GREM_OUT_OF_RANGE", isoObjectJNI.GREM_OUT_OF_RANGE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GeneralResponseStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GeneralResponseStatus.class + " with value " + swigValue);
  }

  private GeneralResponseStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GeneralResponseStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GeneralResponseStatus(String swigName, GeneralResponseStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GeneralResponseStatus[] swigValues = { GREM_STATUS_OK, GREM_DATA_MISSING, GREM_STATE_ERROR, GREM_TIME_SLIPPAGE, GREM_WRONG_ID, GREM_OUT_OF_RANGE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

