/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class GeneralResponseMessageType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GeneralResponseMessageType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeneralResponseMessageType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_GeneralResponseMessageType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatus(GeneralResponseStatus value) {
    isoObjectJNI.GeneralResponseMessageType_status_set(swigCPtr, this, value.swigValue());
  }

  public GeneralResponseStatus getStatus() {
    return GeneralResponseStatus.swigToEnum(isoObjectJNI.GeneralResponseMessageType_status_get(swigCPtr, this));
  }

  public GeneralResponseMessageType() {
    this(isoObjectJNI.new_GeneralResponseMessageType(), true);
  }

}
