/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class GeographicPositionType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GeographicPositionType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeographicPositionType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_GeographicPositionType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLatitude_deg(double value) {
    isoObjectJNI.GeographicPositionType_latitude_deg_set(swigCPtr, this, value);
  }

  public double getLatitude_deg() {
    return isoObjectJNI.GeographicPositionType_latitude_deg_get(swigCPtr, this);
  }

  public void setLongitude_deg(double value) {
    isoObjectJNI.GeographicPositionType_longitude_deg_set(swigCPtr, this, value);
  }

  public double getLongitude_deg() {
    return isoObjectJNI.GeographicPositionType_longitude_deg_get(swigCPtr, this);
  }

  public void setAltitude_m(double value) {
    isoObjectJNI.GeographicPositionType_altitude_m_set(swigCPtr, this, value);
  }

  public double getAltitude_m() {
    return isoObjectJNI.GeographicPositionType_altitude_m_get(swigCPtr, this);
  }

  public void setIsLatitudeValid(boolean value) {
    isoObjectJNI.GeographicPositionType_isLatitudeValid_set(swigCPtr, this, value);
  }

  public boolean getIsLatitudeValid() {
    return isoObjectJNI.GeographicPositionType_isLatitudeValid_get(swigCPtr, this);
  }

  public void setIsLongitudeValid(boolean value) {
    isoObjectJNI.GeographicPositionType_isLongitudeValid_set(swigCPtr, this, value);
  }

  public boolean getIsLongitudeValid() {
    return isoObjectJNI.GeographicPositionType_isLongitudeValid_get(swigCPtr, this);
  }

  public void setIsAltitudeValid(boolean value) {
    isoObjectJNI.GeographicPositionType_isAltitudeValid_set(swigCPtr, this, value);
  }

  public boolean getIsAltitudeValid() {
    return isoObjectJNI.GeographicPositionType_isAltitudeValid_get(swigCPtr, this);
  }

  public GeographicPositionType() {
    this(isoObjectJNI.new_GeographicPositionType(), true);
  }

}
