/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class HeabMessageDataType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HeabMessageDataType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HeabMessageDataType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_HeabMessageDataType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTransmitterID(long value) {
    isoObjectJNI.HeabMessageDataType_transmitterID_set(swigCPtr, this, value);
  }

  public long getTransmitterID() {
    return isoObjectJNI.HeabMessageDataType_transmitterID_get(swigCPtr, this);
  }

  public void setDataTimestamp(timeval value) {
    isoObjectJNI.HeabMessageDataType_dataTimestamp_set(swigCPtr, this, timeval.getCPtr(value), value);
  }

  public timeval getDataTimestamp() {
    long cPtr = isoObjectJNI.HeabMessageDataType_dataTimestamp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new timeval(cPtr, false);
  }

  public void setControlCenterStatus(ControlCenterStatusType value) {
    isoObjectJNI.HeabMessageDataType_controlCenterStatus_set(swigCPtr, this, value.swigValue());
  }

  public ControlCenterStatusType getControlCenterStatus() {
    return ControlCenterStatusType.swigToEnum(isoObjectJNI.HeabMessageDataType_controlCenterStatus_get(swigCPtr, this));
  }

  public HeabMessageDataType() {
    this(isoObjectJNI.new_HeabMessageDataType(), true);
  }

}
