/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public interface isoObjectConstants {
  public final static int HEAB_FREQUENCY_HZ = isoObjectJNI.HEAB_FREQUENCY_HZ_get();
  public final static int MONR_EXPECTED_FREQUENCY_HZ = isoObjectJNI.MONR_EXPECTED_FREQUENCY_HZ_get();
}
