/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public final class ISOUnitType {
  public final static ISOUnitType ISO_UNIT_TYPE_STEERING_DEGREES = new ISOUnitType("ISO_UNIT_TYPE_STEERING_DEGREES", isoObjectJNI.ISO_UNIT_TYPE_STEERING_DEGREES_get());
  public final static ISOUnitType ISO_UNIT_TYPE_STEERING_PERCENTAGE = new ISOUnitType("ISO_UNIT_TYPE_STEERING_PERCENTAGE", isoObjectJNI.ISO_UNIT_TYPE_STEERING_PERCENTAGE_get());
  public final static ISOUnitType ISO_UNIT_TYPE_SPEED_METER_SECOND = new ISOUnitType("ISO_UNIT_TYPE_SPEED_METER_SECOND", isoObjectJNI.ISO_UNIT_TYPE_SPEED_METER_SECOND_get());
  public final static ISOUnitType ISO_UNIT_TYPE_SPEED_PERCENTAGE = new ISOUnitType("ISO_UNIT_TYPE_SPEED_PERCENTAGE", isoObjectJNI.ISO_UNIT_TYPE_SPEED_PERCENTAGE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ISOUnitType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ISOUnitType.class + " with value " + swigValue);
  }

  private ISOUnitType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ISOUnitType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ISOUnitType(String swigName, ISOUnitType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ISOUnitType[] swigValues = { ISO_UNIT_TYPE_STEERING_DEGREES, ISO_UNIT_TYPE_STEERING_PERCENTAGE, ISO_UNIT_TYPE_SPEED_METER_SECOND, ISO_UNIT_TYPE_SPEED_PERCENTAGE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

