/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class ObjectMonitorType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjectMonitorType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectMonitorType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_ObjectMonitorType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIsTimestampValid(boolean value) {
    isoObjectJNI.ObjectMonitorType_isTimestampValid_set(swigCPtr, this, value);
  }

  public boolean getIsTimestampValid() {
    return isoObjectJNI.ObjectMonitorType_isTimestampValid_get(swigCPtr, this);
  }

  public void setTimestamp(timeval value) {
    isoObjectJNI.ObjectMonitorType_timestamp_set(swigCPtr, this, timeval.getCPtr(value), value);
  }

  public timeval getTimestamp() {
    long cPtr = isoObjectJNI.ObjectMonitorType_timestamp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new timeval(cPtr, false);
  }

  public void setPosition(CartesianPosition value) {
    isoObjectJNI.ObjectMonitorType_position_set(swigCPtr, this, CartesianPosition.getCPtr(value), value);
  }

  public CartesianPosition getPosition() {
    long cPtr = isoObjectJNI.ObjectMonitorType_position_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CartesianPosition(cPtr, false);
  }

  public void setSpeed(SpeedType value) {
    isoObjectJNI.ObjectMonitorType_speed_set(swigCPtr, this, SpeedType.getCPtr(value), value);
  }

  public SpeedType getSpeed() {
    long cPtr = isoObjectJNI.ObjectMonitorType_speed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SpeedType(cPtr, false);
  }

  public void setAcceleration(AccelerationType value) {
    isoObjectJNI.ObjectMonitorType_acceleration_set(swigCPtr, this, AccelerationType.getCPtr(value), value);
  }

  public AccelerationType getAcceleration() {
    long cPtr = isoObjectJNI.ObjectMonitorType_acceleration_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AccelerationType(cPtr, false);
  }

  public void setDrivingDirection(DriveDirectionType value) {
    isoObjectJNI.ObjectMonitorType_drivingDirection_set(swigCPtr, this, value.swigValue());
  }

  public DriveDirectionType getDrivingDirection() {
    return DriveDirectionType.swigToEnum(isoObjectJNI.ObjectMonitorType_drivingDirection_get(swigCPtr, this));
  }

  public void setState(ObjectStateType value) {
    isoObjectJNI.ObjectMonitorType_state_set(swigCPtr, this, value.swigValue());
  }

  public ObjectStateType getState() {
    return ObjectStateType.swigToEnum(isoObjectJNI.ObjectMonitorType_state_get(swigCPtr, this));
  }

  public void setArmReadiness(ObjectArmReadinessType value) {
    isoObjectJNI.ObjectMonitorType_armReadiness_set(swigCPtr, this, value.swigValue());
  }

  public ObjectArmReadinessType getArmReadiness() {
    return ObjectArmReadinessType.swigToEnum(isoObjectJNI.ObjectMonitorType_armReadiness_get(swigCPtr, this));
  }

  public void setError(ObjectErrorType value) {
    isoObjectJNI.ObjectMonitorType_error_set(swigCPtr, this, ObjectErrorType.getCPtr(value), value);
  }

  public ObjectErrorType getError() {
    long cPtr = isoObjectJNI.ObjectMonitorType_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ObjectErrorType(cPtr, false);
  }

  public ObjectMonitorType() {
    this(isoObjectJNI.new_ObjectMonitorType(), true);
  }

}
