/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public final class ObjectArmReadinessType {
  public final static ObjectArmReadinessType OBJECT_NOT_READY_TO_ARM = new ObjectArmReadinessType("OBJECT_NOT_READY_TO_ARM");
  public final static ObjectArmReadinessType OBJECT_READY_TO_ARM = new ObjectArmReadinessType("OBJECT_READY_TO_ARM");
  public final static ObjectArmReadinessType OBJECT_READY_TO_ARM_UNAVAILABLE = new ObjectArmReadinessType("OBJECT_READY_TO_ARM_UNAVAILABLE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjectArmReadinessType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjectArmReadinessType.class + " with value " + swigValue);
  }

  private ObjectArmReadinessType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjectArmReadinessType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjectArmReadinessType(String swigName, ObjectArmReadinessType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjectArmReadinessType[] swigValues = { OBJECT_NOT_READY_TO_ARM, OBJECT_READY_TO_ARM, OBJECT_READY_TO_ARM_UNAVAILABLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

