/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class ObjectErrorType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjectErrorType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectErrorType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_ObjectErrorType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAbortRequest(boolean value) {
    isoObjectJNI.ObjectErrorType_abortRequest_set(swigCPtr, this, value);
  }

  public boolean getAbortRequest() {
    return isoObjectJNI.ObjectErrorType_abortRequest_get(swigCPtr, this);
  }

  public void setOutsideGeofence(boolean value) {
    isoObjectJNI.ObjectErrorType_outsideGeofence_set(swigCPtr, this, value);
  }

  public boolean getOutsideGeofence() {
    return isoObjectJNI.ObjectErrorType_outsideGeofence_get(swigCPtr, this);
  }

  public void setBadPositioningAccuracy(boolean value) {
    isoObjectJNI.ObjectErrorType_badPositioningAccuracy_set(swigCPtr, this, value);
  }

  public boolean getBadPositioningAccuracy() {
    return isoObjectJNI.ObjectErrorType_badPositioningAccuracy_get(swigCPtr, this);
  }

  public void setEngineFault(boolean value) {
    isoObjectJNI.ObjectErrorType_engineFault_set(swigCPtr, this, value);
  }

  public boolean getEngineFault() {
    return isoObjectJNI.ObjectErrorType_engineFault_get(swigCPtr, this);
  }

  public void setBatteryFault(boolean value) {
    isoObjectJNI.ObjectErrorType_batteryFault_set(swigCPtr, this, value);
  }

  public boolean getBatteryFault() {
    return isoObjectJNI.ObjectErrorType_batteryFault_get(swigCPtr, this);
  }

  public void setSyncPointEnded(boolean value) {
    isoObjectJNI.ObjectErrorType_syncPointEnded_set(swigCPtr, this, value);
  }

  public boolean getSyncPointEnded() {
    return isoObjectJNI.ObjectErrorType_syncPointEnded_get(swigCPtr, this);
  }

  public void setUnknownError(boolean value) {
    isoObjectJNI.ObjectErrorType_unknownError_set(swigCPtr, this, value);
  }

  public boolean getUnknownError() {
    return isoObjectJNI.ObjectErrorType_unknownError_get(swigCPtr, this);
  }

  public ObjectErrorType() {
    this(isoObjectJNI.new_ObjectErrorType(), true);
  }

}
