/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class ObjectSettingsType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjectSettingsType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectSettingsType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_ObjectSettingsType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDesiredTransmitterID(long value) {
    isoObjectJNI.ObjectSettingsType_desiredTransmitterID_set(swigCPtr, this, value);
  }

  public long getDesiredTransmitterID() {
    return isoObjectJNI.ObjectSettingsType_desiredTransmitterID_get(swigCPtr, this);
  }

  public void setCoordinateSystemOrigin(GeographicPositionType value) {
    isoObjectJNI.ObjectSettingsType_coordinateSystemOrigin_set(swigCPtr, this, GeographicPositionType.getCPtr(value), value);
  }

  public GeographicPositionType getCoordinateSystemOrigin() {
    long cPtr = isoObjectJNI.ObjectSettingsType_coordinateSystemOrigin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GeographicPositionType(cPtr, false);
  }

  public void setCurrentTime(timeval value) {
    isoObjectJNI.ObjectSettingsType_currentTime_set(swigCPtr, this, timeval.getCPtr(value), value);
  }

  public timeval getCurrentTime() {
    long cPtr = isoObjectJNI.ObjectSettingsType_currentTime_get(swigCPtr, this);
    return (cPtr == 0) ? null : new timeval(cPtr, false);
  }

  public void setMaxPositionDeviation_m(double value) {
    isoObjectJNI.ObjectSettingsType_maxPositionDeviation_m_set(swigCPtr, this, value);
  }

  public double getMaxPositionDeviation_m() {
    return isoObjectJNI.ObjectSettingsType_maxPositionDeviation_m_get(swigCPtr, this);
  }

  public void setMaxLateralDeviation_m(double value) {
    isoObjectJNI.ObjectSettingsType_maxLateralDeviation_m_set(swigCPtr, this, value);
  }

  public double getMaxLateralDeviation_m() {
    return isoObjectJNI.ObjectSettingsType_maxLateralDeviation_m_get(swigCPtr, this);
  }

  public void setMinRequiredPositioningAccuracy_m(double value) {
    isoObjectJNI.ObjectSettingsType_minRequiredPositioningAccuracy_m_set(swigCPtr, this, value);
  }

  public double getMinRequiredPositioningAccuracy_m() {
    return isoObjectJNI.ObjectSettingsType_minRequiredPositioningAccuracy_m_get(swigCPtr, this);
  }

  public void setIsTransmitterIDValid(boolean value) {
    isoObjectJNI.ObjectSettingsType_isTransmitterIDValid_set(swigCPtr, this, value);
  }

  public boolean getIsTransmitterIDValid() {
    return isoObjectJNI.ObjectSettingsType_isTransmitterIDValid_get(swigCPtr, this);
  }

  public void setIsPositionDeviationLimited(boolean value) {
    isoObjectJNI.ObjectSettingsType_isPositionDeviationLimited_set(swigCPtr, this, value);
  }

  public boolean getIsPositionDeviationLimited() {
    return isoObjectJNI.ObjectSettingsType_isPositionDeviationLimited_get(swigCPtr, this);
  }

  public void setIsLateralDeviationLimited(boolean value) {
    isoObjectJNI.ObjectSettingsType_isLateralDeviationLimited_set(swigCPtr, this, value);
  }

  public boolean getIsLateralDeviationLimited() {
    return isoObjectJNI.ObjectSettingsType_isLateralDeviationLimited_get(swigCPtr, this);
  }

  public void setIsPositioningAccuracyRequired(boolean value) {
    isoObjectJNI.ObjectSettingsType_isPositioningAccuracyRequired_set(swigCPtr, this, value);
  }

  public boolean getIsPositioningAccuracyRequired() {
    return isoObjectJNI.ObjectSettingsType_isPositioningAccuracyRequired_get(swigCPtr, this);
  }

  public void setIsTimestampValid(boolean value) {
    isoObjectJNI.ObjectSettingsType_isTimestampValid_set(swigCPtr, this, value);
  }

  public boolean getIsTimestampValid() {
    return isoObjectJNI.ObjectSettingsType_isTimestampValid_get(swigCPtr, this);
  }

  public ObjectSettingsType() {
    this(isoObjectJNI.new_ObjectSettingsType(), true);
  }

}
