/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class ObjectPropertiesType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ObjectPropertiesType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectPropertiesType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_ObjectPropertiesType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setObjectID(long value) {
    isoObjectJNI.ObjectPropertiesType_objectID_set(swigCPtr, this, value);
  }

  public long getObjectID() {
    return isoObjectJNI.ObjectPropertiesType_objectID_get(swigCPtr, this);
  }

  public void setObjectType(ObjectCategoryType value) {
    isoObjectJNI.ObjectPropertiesType_objectType_set(swigCPtr, this, value.swigValue());
  }

  public ObjectCategoryType getObjectType() {
    return ObjectCategoryType.swigToEnum(isoObjectJNI.ObjectPropertiesType_objectType_get(swigCPtr, this));
  }

  public void setActorType(ActorType value) {
    isoObjectJNI.ObjectPropertiesType_actorType_set(swigCPtr, this, value.swigValue());
  }

  public ActorType getActorType() {
    return ActorType.swigToEnum(isoObjectJNI.ObjectPropertiesType_actorType_get(swigCPtr, this));
  }

  public void setOperationMode(OperationMode value) {
    isoObjectJNI.ObjectPropertiesType_operationMode_set(swigCPtr, this, value.swigValue());
  }

  public OperationMode getOperationMode() {
    return OperationMode.swigToEnum(isoObjectJNI.ObjectPropertiesType_operationMode_get(swigCPtr, this));
  }

  public void setMass_kg(double value) {
    isoObjectJNI.ObjectPropertiesType_mass_kg_set(swigCPtr, this, value);
  }

  public double getMass_kg() {
    return isoObjectJNI.ObjectPropertiesType_mass_kg_get(swigCPtr, this);
  }

  public void setObjectXDimension_m(double value) {
    isoObjectJNI.ObjectPropertiesType_objectXDimension_m_set(swigCPtr, this, value);
  }

  public double getObjectXDimension_m() {
    return isoObjectJNI.ObjectPropertiesType_objectXDimension_m_get(swigCPtr, this);
  }

  public void setObjectYDimension_m(double value) {
    isoObjectJNI.ObjectPropertiesType_objectYDimension_m_set(swigCPtr, this, value);
  }

  public double getObjectYDimension_m() {
    return isoObjectJNI.ObjectPropertiesType_objectYDimension_m_get(swigCPtr, this);
  }

  public void setObjectZDimension_m(double value) {
    isoObjectJNI.ObjectPropertiesType_objectZDimension_m_set(swigCPtr, this, value);
  }

  public double getObjectZDimension_m() {
    return isoObjectJNI.ObjectPropertiesType_objectZDimension_m_get(swigCPtr, this);
  }

  public void setPositionDisplacementX_m(double value) {
    isoObjectJNI.ObjectPropertiesType_positionDisplacementX_m_set(swigCPtr, this, value);
  }

  public double getPositionDisplacementX_m() {
    return isoObjectJNI.ObjectPropertiesType_positionDisplacementX_m_get(swigCPtr, this);
  }

  public void setPositionDisplacementY_m(double value) {
    isoObjectJNI.ObjectPropertiesType_positionDisplacementY_m_set(swigCPtr, this, value);
  }

  public double getPositionDisplacementY_m() {
    return isoObjectJNI.ObjectPropertiesType_positionDisplacementY_m_get(swigCPtr, this);
  }

  public void setPositionDisplacementZ_m(double value) {
    isoObjectJNI.ObjectPropertiesType_positionDisplacementZ_m_set(swigCPtr, this, value);
  }

  public double getPositionDisplacementZ_m() {
    return isoObjectJNI.ObjectPropertiesType_positionDisplacementZ_m_get(swigCPtr, this);
  }

  public void setIsMassValid(boolean value) {
    isoObjectJNI.ObjectPropertiesType_isMassValid_set(swigCPtr, this, value);
  }

  public boolean getIsMassValid() {
    return isoObjectJNI.ObjectPropertiesType_isMassValid_get(swigCPtr, this);
  }

  public void setIsObjectXDimensionValid(boolean value) {
    isoObjectJNI.ObjectPropertiesType_isObjectXDimensionValid_set(swigCPtr, this, value);
  }

  public boolean getIsObjectXDimensionValid() {
    return isoObjectJNI.ObjectPropertiesType_isObjectXDimensionValid_get(swigCPtr, this);
  }

  public void setIsObjectYDimensionValid(boolean value) {
    isoObjectJNI.ObjectPropertiesType_isObjectYDimensionValid_set(swigCPtr, this, value);
  }

  public boolean getIsObjectYDimensionValid() {
    return isoObjectJNI.ObjectPropertiesType_isObjectYDimensionValid_get(swigCPtr, this);
  }

  public void setIsObjectZDimensionValid(boolean value) {
    isoObjectJNI.ObjectPropertiesType_isObjectZDimensionValid_set(swigCPtr, this, value);
  }

  public boolean getIsObjectZDimensionValid() {
    return isoObjectJNI.ObjectPropertiesType_isObjectZDimensionValid_get(swigCPtr, this);
  }

  public void setIsObjectXDisplacementValid(boolean value) {
    isoObjectJNI.ObjectPropertiesType_isObjectXDisplacementValid_set(swigCPtr, this, value);
  }

  public boolean getIsObjectXDisplacementValid() {
    return isoObjectJNI.ObjectPropertiesType_isObjectXDisplacementValid_get(swigCPtr, this);
  }

  public void setIsObjectYDisplacementValid(boolean value) {
    isoObjectJNI.ObjectPropertiesType_isObjectYDisplacementValid_set(swigCPtr, this, value);
  }

  public boolean getIsObjectYDisplacementValid() {
    return isoObjectJNI.ObjectPropertiesType_isObjectYDisplacementValid_get(swigCPtr, this);
  }

  public void setIsObjectZDisplacementValid(boolean value) {
    isoObjectJNI.ObjectPropertiesType_isObjectZDisplacementValid_set(swigCPtr, this, value);
  }

  public boolean getIsObjectZDisplacementValid() {
    return isoObjectJNI.ObjectPropertiesType_isObjectZDisplacementValid_get(swigCPtr, this);
  }

  public ObjectPropertiesType() {
    this(isoObjectJNI.new_ObjectPropertiesType(), true);
  }

}
