/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public final class ObjectStateType {
  public final static ObjectStateType OBJECT_STATE_UNKNOWN = new ObjectStateType("OBJECT_STATE_UNKNOWN");
  public final static ObjectStateType OBJECT_STATE_DISARMED = new ObjectStateType("OBJECT_STATE_DISARMED");
  public final static ObjectStateType OBJECT_STATE_ARMED = new ObjectStateType("OBJECT_STATE_ARMED");
  public final static ObjectStateType OBJECT_STATE_RUNNING = new ObjectStateType("OBJECT_STATE_RUNNING");
  public final static ObjectStateType OBJECT_STATE_POSTRUN = new ObjectStateType("OBJECT_STATE_POSTRUN");
  public final static ObjectStateType OBJECT_STATE_ABORTING = new ObjectStateType("OBJECT_STATE_ABORTING");
  public final static ObjectStateType OBJECT_STATE_REMOTE_CONTROL = new ObjectStateType("OBJECT_STATE_REMOTE_CONTROL");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ObjectStateType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ObjectStateType.class + " with value " + swigValue);
  }

  private ObjectStateType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ObjectStateType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ObjectStateType(String swigName, ObjectStateType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ObjectStateType[] swigValues = { OBJECT_STATE_UNKNOWN, OBJECT_STATE_DISARMED, OBJECT_STATE_ARMED, OBJECT_STATE_RUNNING, OBJECT_STATE_POSTRUN, OBJECT_STATE_ABORTING, OBJECT_STATE_REMOTE_CONTROL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

