/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class RdciMessageDataType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RdciMessageDataType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RdciMessageDataType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_RdciMessageDataType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMessageID(int value) {
    isoObjectJNI.RdciMessageDataType_messageID_set(swigCPtr, this, value);
  }

  public int getMessageID() {
    return isoObjectJNI.RdciMessageDataType_messageID_get(swigCPtr, this);
  }

  public RdciMessageDataType() {
    this(isoObjectJNI.new_RdciMessageDataType(), true);
  }

}
