/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class RemoteControlManoeuvreMessageType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RemoteControlManoeuvreMessageType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RemoteControlManoeuvreMessageType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_RemoteControlManoeuvreMessageType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStatus(short value) {
    isoObjectJNI.RemoteControlManoeuvreMessageType_status_set(swigCPtr, this, value);
  }

  public short getStatus() {
    return isoObjectJNI.RemoteControlManoeuvreMessageType_status_get(swigCPtr, this);
  }

  static public class steeringMan {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected steeringMan(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(steeringMan obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          isoObjectJNI.delete_RemoteControlManoeuvreMessageType_steeringMan(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setPct(double value) {
      isoObjectJNI.RemoteControlManoeuvreMessageType_steeringMan_pct_set(swigCPtr, this, value);
    }
  
    public double getPct() {
      return isoObjectJNI.RemoteControlManoeuvreMessageType_steeringMan_pct_get(swigCPtr, this);
    }
  
    public void setRad(double value) {
      isoObjectJNI.RemoteControlManoeuvreMessageType_steeringMan_rad_set(swigCPtr, this, value);
    }
  
    public double getRad() {
      return isoObjectJNI.RemoteControlManoeuvreMessageType_steeringMan_rad_get(swigCPtr, this);
    }
  
    public steeringMan() {
      this(isoObjectJNI.new_RemoteControlManoeuvreMessageType_steeringMan(), true);
    }
  
  }

  public void setSteeringManoeuvre(RemoteControlManoeuvreMessageType.steeringMan value) {
    isoObjectJNI.RemoteControlManoeuvreMessageType_steeringManoeuvre_set(swigCPtr, this, RemoteControlManoeuvreMessageType.steeringMan.getCPtr(value), value);
  }

  public RemoteControlManoeuvreMessageType.steeringMan getSteeringManoeuvre() {
    long cPtr = isoObjectJNI.RemoteControlManoeuvreMessageType_steeringManoeuvre_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RemoteControlManoeuvreMessageType.steeringMan(cPtr, false);
  }

  static public class speedMan {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected speedMan(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(speedMan obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          isoObjectJNI.delete_RemoteControlManoeuvreMessageType_speedMan(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setPct(double value) {
      isoObjectJNI.RemoteControlManoeuvreMessageType_speedMan_pct_set(swigCPtr, this, value);
    }
  
    public double getPct() {
      return isoObjectJNI.RemoteControlManoeuvreMessageType_speedMan_pct_get(swigCPtr, this);
    }
  
    public void setM_s(double value) {
      isoObjectJNI.RemoteControlManoeuvreMessageType_speedMan_m_s_set(swigCPtr, this, value);
    }
  
    public double getM_s() {
      return isoObjectJNI.RemoteControlManoeuvreMessageType_speedMan_m_s_get(swigCPtr, this);
    }
  
    public speedMan() {
      this(isoObjectJNI.new_RemoteControlManoeuvreMessageType_speedMan(), true);
    }
  
  }

  public void setSpeedManoeuvre(RemoteControlManoeuvreMessageType.speedMan value) {
    isoObjectJNI.RemoteControlManoeuvreMessageType_speedManoeuvre_set(swigCPtr, this, RemoteControlManoeuvreMessageType.speedMan.getCPtr(value), value);
  }

  public RemoteControlManoeuvreMessageType.speedMan getSpeedManoeuvre() {
    long cPtr = isoObjectJNI.RemoteControlManoeuvreMessageType_speedManoeuvre_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RemoteControlManoeuvreMessageType.speedMan(cPtr, false);
  }

  public void setCommand(RemoteControlManoeuvreCommandType value) {
    isoObjectJNI.RemoteControlManoeuvreMessageType_command_set(swigCPtr, this, value.swigValue());
  }

  public RemoteControlManoeuvreCommandType getCommand() {
    return RemoteControlManoeuvreCommandType.swigToEnum(isoObjectJNI.RemoteControlManoeuvreMessageType_command_get(swigCPtr, this));
  }

  public void setSteeringUnit(ISOUnitType value) {
    isoObjectJNI.RemoteControlManoeuvreMessageType_steeringUnit_set(swigCPtr, this, value.swigValue());
  }

  public ISOUnitType getSteeringUnit() {
    return ISOUnitType.swigToEnum(isoObjectJNI.RemoteControlManoeuvreMessageType_steeringUnit_get(swigCPtr, this));
  }

  public void setSpeedUnit(ISOUnitType value) {
    isoObjectJNI.RemoteControlManoeuvreMessageType_speedUnit_set(swigCPtr, this, value.swigValue());
  }

  public ISOUnitType getSpeedUnit() {
    return ISOUnitType.swigToEnum(isoObjectJNI.RemoteControlManoeuvreMessageType_speedUnit_get(swigCPtr, this));
  }

  public void setIsSteeringManoeuvreValid(boolean value) {
    isoObjectJNI.RemoteControlManoeuvreMessageType_isSteeringManoeuvreValid_set(swigCPtr, this, value);
  }

  public boolean getIsSteeringManoeuvreValid() {
    return isoObjectJNI.RemoteControlManoeuvreMessageType_isSteeringManoeuvreValid_get(swigCPtr, this);
  }

  public void setIsSpeedManoeuvreValid(boolean value) {
    isoObjectJNI.RemoteControlManoeuvreMessageType_isSpeedManoeuvreValid_set(swigCPtr, this, value);
  }

  public boolean getIsSpeedManoeuvreValid() {
    return isoObjectJNI.RemoteControlManoeuvreMessageType_isSpeedManoeuvreValid_get(swigCPtr, this);
  }

  public RemoteControlManoeuvreMessageType() {
    this(isoObjectJNI.new_RemoteControlManoeuvreMessageType(), true);
  }

}
