/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class SpeedType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SpeedType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpeedType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_SpeedType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLongitudinal_m_s(double value) {
    isoObjectJNI.SpeedType_longitudinal_m_s_set(swigCPtr, this, value);
  }

  public double getLongitudinal_m_s() {
    return isoObjectJNI.SpeedType_longitudinal_m_s_get(swigCPtr, this);
  }

  public void setLateral_m_s(double value) {
    isoObjectJNI.SpeedType_lateral_m_s_set(swigCPtr, this, value);
  }

  public double getLateral_m_s() {
    return isoObjectJNI.SpeedType_lateral_m_s_get(swigCPtr, this);
  }

  public void setIsLongitudinalValid(boolean value) {
    isoObjectJNI.SpeedType_isLongitudinalValid_set(swigCPtr, this, value);
  }

  public boolean getIsLongitudinalValid() {
    return isoObjectJNI.SpeedType_isLongitudinalValid_get(swigCPtr, this);
  }

  public void setIsLateralValid(boolean value) {
    isoObjectJNI.SpeedType_isLateralValid_set(swigCPtr, this, value);
  }

  public boolean getIsLateralValid() {
    return isoObjectJNI.SpeedType_isLateralValid_get(swigCPtr, this);
  }

  public SpeedType() {
    this(isoObjectJNI.new_SpeedType(), true);
  }

}
