/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class State {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected State(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(State obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_State(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ObjectStateID getStateID() {
    return ObjectStateID.swigToEnum(isoObjectJNI.State_getStateID(swigCPtr, this));
  }

  public SWIGTYPE_p_std__string getName() {
    return new SWIGTYPE_p_std__string(isoObjectJNI.State_getName(swigCPtr, this), true);
  }

  public void handleEvent(TestObject arg0, EventType arg1) {
    isoObjectJNI.State_handleEvent(swigCPtr, this, TestObject.getCPtr(arg0), arg0, arg1.swigValue());
  }

}
