/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class TestObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public TestObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TestObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_TestObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void disconnect() {
    isoObjectJNI.TestObject_disconnect(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string getCurrentStateName() {
    return new SWIGTYPE_p_std__string(isoObjectJNI.TestObject_getCurrentStateName(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string getName() {
    return new SWIGTYPE_p_std__string(isoObjectJNI.TestObject_getName(swigCPtr, this), true);
  }

  public CartesianPosition getPosition() {
    return new CartesianPosition(isoObjectJNI.TestObject_getPosition(swigCPtr, this), true);
  }

  public SpeedType getSpeed() {
    return new SpeedType(isoObjectJNI.TestObject_getSpeed(swigCPtr, this), true);
  }

  public AccelerationType getAcceleration() {
    return new AccelerationType(isoObjectJNI.TestObject_getAcceleration(swigCPtr, this), true);
  }

  public DriveDirectionType getDriveDirection() {
    return DriveDirectionType.swigToEnum(isoObjectJNI.TestObject_getDriveDirection(swigCPtr, this));
  }

  public SWIGTYPE_p_TrajectoryHeaderType getTrajectoryHeader() {
    return new SWIGTYPE_p_TrajectoryHeaderType(isoObjectJNI.TestObject_getTrajectoryHeader(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__vectorT_TrajectoryWaypointType_t getTrajectory() {
    return new SWIGTYPE_p_std__vectorT_TrajectoryWaypointType_t(isoObjectJNI.TestObject_getTrajectory(swigCPtr, this), true);
  }

  public GeographicPositionType getOrigin() {
    return new GeographicPositionType(isoObjectJNI.TestObject_getOrigin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__string getLocalIP() {
    return new SWIGTYPE_p_std__string(isoObjectJNI.TestObject_getLocalIP(swigCPtr, this), true);
  }

  public long getTransmitterID() {
    return isoObjectJNI.TestObject_getTransmitterID(swigCPtr, this);
  }

}
