/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.isoObject;

public class Transition {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Transition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Transition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        isoObjectJNI.delete_Transition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSource(ObjectStateID value) {
    isoObjectJNI.Transition_source_set(swigCPtr, this, value.swigValue());
  }

  public ObjectStateID getSource() {
    return ObjectStateID.swigToEnum(isoObjectJNI.Transition_source_get(swigCPtr, this));
  }

  public void setEvent(EventType value) {
    isoObjectJNI.Transition_event_set(swigCPtr, this, value.swigValue());
  }

  public EventType getEvent() {
    return EventType.swigToEnum(isoObjectJNI.Transition_event_get(swigCPtr, this));
  }

  public void setTarget(ObjectStateID value) {
    isoObjectJNI.Transition_target_set(swigCPtr, this, value.swigValue());
  }

  public ObjectStateID getTarget() {
    return ObjectStateID.swigToEnum(isoObjectJNI.Transition_target_get(swigCPtr, this));
  }

  public Transition() {
    this(isoObjectJNI.new_Transition(), true);
  }

}
